In [1]:
import torch
import numpy as np
from pathlib import Path
import plotly.graph_objs as go


from initialization import NeuralSurfaceReconstruction

In [2]:
nsr = NeuralSurfaceReconstruction(
    data=Path("../data/calculator"),
)

In [3]:
_, st = nsr.query_pixel_sample_points(0, N_query_points=100, t_size=0.15,
                                        _pixel_grid_width_step=100.0,
                                        _pixel_grid_height_step=100.0,
                                        _scale=1.0)
stx, sty, stz = np.hsplit(st.reshape(-1, 3), 3)

In [4]:
st_i = st[:, 60]

In [5]:
ft = ((nsr.fg_V.min_x < st_i[:, 0]) & (st_i[:, 0] < nsr.fg_V.max_x) &
 (nsr.fg_V.min_y < st_i[:, 1]) & (st_i[:, 1] < nsr.fg_V.max_y) &
 (nsr.fg_V.min_z < st_i[:, 2]) & (st_i[:, 2] < nsr.fg_V.max_z)).astype(int)

fst = st_i*ft[:, np.newaxis]
fstx, fsty, fstz = np.hsplit(fst.reshape(-1, 3), 3)

In [6]:
bt = ((nsr.bg_V.min_x < st_i[:, 0]) & (st_i[:, 0] < nsr.bg_V.max_x) &
 (nsr.bg_V.min_y < st_i[:, 1]) & (st_i[:, 1] < nsr.bg_V.max_y) &
 (nsr.bg_V.min_z < st_i[:, 2]) & (st_i[:, 2] < nsr.bg_V.max_z)).astype(int)

bst = st_i*bt[:, np.newaxis]*(1-ft[:, np.newaxis])
bstx, bsty, bstz = np.hsplit(bst.reshape(-1, 3), 3)

In [7]:
FG_STEP_SIZE = nsr.fg_V.grid_pos[0][0][0][0]-nsr.fg_V.grid_pos[0][1][0][0]
FG_ROUNDING_OFS = [
    nsr.fg_V.grid_pos[0, :, 0, 0][0],  # x
    nsr.fg_V.grid_pos[1, 0, :, 0][0],  # y
    nsr.fg_V.grid_pos[2, 0, 0, :][0]   # z
]
# fst
rfst = np.floor((fst+FG_ROUNDING_OFS)/FG_STEP_SIZE)*FG_STEP_SIZE-FG_ROUNDING_OFS
rfstx, rfsty, rfstz = np.hsplit(rfst.reshape(-1, 3), 3)

In [8]:
BG_STEP_SIZE = nsr.bg_V.grid_pos[0][0][0][0]-nsr.bg_V.grid_pos[0][1][0][0]
BG_ROUNDING_OFS = [
    nsr.bg_V.grid_pos[0, :, 0, 0][0],  # x
    nsr.bg_V.grid_pos[1, 0, :, 0][0],  # y
    nsr.bg_V.grid_pos[2, 0, 0, :][0]   # z
]
rbst = np.floor((bst+BG_ROUNDING_OFS)/BG_STEP_SIZE)*BG_STEP_SIZE-BG_ROUNDING_OFS
rbstx, rbsty, rbstz = np.hsplit(rbst.reshape(-1, 3), 3)

In [9]:
go.Figure(data=[
    go.Scatter3d(
        x=nsr.fg_V.grid_pos[0].flatten(),
        y=nsr.fg_V.grid_pos[1].flatten(),
        z=nsr.fg_V.grid_pos[2].flatten(),
        mode='markers',
        marker={
            'size': 10,
            "color": nsr.fg_V.sdf.flatten(),
            'opacity': 0.5,
            "colorbar": {
                "thickness": 10,
            }
        }
    ),
    go.Scatter3d(
        x=nsr.bg_V.grid_pos[0].flatten(),
        y=nsr.bg_V.grid_pos[1].flatten(),
        z=nsr.bg_V.grid_pos[2].flatten(),
        mode='markers',
        marker={
            'size': 10,
            "color": nsr.bg_V.sdf.flatten(),
            'opacity': 0.5,
            "colorbar": {
                "thickness": 10,
            }
        }
    ),
    # go.Scatter3d(
    #     x=stx.flatten(),
    #     y=sty.flatten(),
    #     z=stz.flatten(),
    #     mode='markers',
    #     marker={
    #         'size': 1,
    #         'opacity': 0.2,
    #     }
    # ),
    go.Scatter3d(
        x=rfstx.flatten(),
        y=rfsty.flatten(),
        z=rfstz.flatten(),
        mode='markers',
        marker={
            'size': 3,
            'opacity': 0.9,
        }
    ),
    go.Scatter3d(
        x=rbstx.flatten(),
        y=rbsty.flatten(),
        z=rbstz.flatten(),
        mode='markers',
        marker={
            'size': 3,
            'opacity': 0.9,
        }
    ),
], layout=go.Layout(
    margin={'l': 0, 'r': 0, 'b': 0, 't': 0},
    scene=dict(
        aspectmode="cube",
        xaxis=dict(range=[-30, 30]),  # Set x-axis range
        yaxis=dict(range=[-30, 30]),  # Set y-axis range
        zaxis=dict(range=[-30, 30])   # Set z-axis range
    )
))

In [10]:
rfstx

array([[ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [

In [11]:
# np.where(np.isclose(nsr.fg_V.grid_pos[0, :, 0, 0], px, FLOAT_TOLERANCE))[0][0]
FLOAT_TOLERANCE: float = 1e-5

vx = np.where(np.isclose(nsr.fg_V.grid_pos[0, :, 0, 0], rfstx, FLOAT_TOLERANCE))[0]
vy = np.where(np.isclose(nsr.fg_V.grid_pos[1, 0, :, 0], rfsty, FLOAT_TOLERANCE))[0]
vz = np.where(np.isclose(nsr.fg_V.grid_pos[2, 0, 0, :], rfstz, FLOAT_TOLERANCE))[0]

In [12]:
vx

array([], dtype=int64)

In [13]:
rfstx

array([[ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [ 0.05],
       [

In [14]:
nsr.fg_V.grid_pos[0, :, 0, 0]

array([-3.25, -3.05, -2.85, -2.65, -2.45, -2.25, -2.05, -1.85, -1.65,
       -1.45, -1.25, -1.05, -0.85, -0.65, -0.45, -0.25])

In [15]:
np.isclose(nsr.fg_V.grid_pos[0, :, 0, 0], rfstx, FLOAT_TOLERANCE)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [16]:
np.abs(rfsty - nsr.fg_V.grid_pos[1, 0, :, 0]).argmin(axis=1)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [17]:
rfst[:, :, np.newaxis]

array([[[0.05],
        [0.  ],
        [0.2 ]],

       [[0.05],
        [0.  ],
        [0.2 ]],

       [[0.05],
        [0.  ],
        [0.2 ]],

       ...,

       [[0.05],
        [0.  ],
        [0.2 ]],

       [[0.05],
        [0.  ],
        [0.2 ]],

       [[0.05],
        [0.  ],
        [0.2 ]]])

In [18]:
np.array([nsr.fg_V.grid_pos[0, :, 0, 0],
          nsr.fg_V.grid_pos[1, 0, :, 0],
          nsr.fg_V.grid_pos[2, 0, 0, :]])

array([[-3.25, -3.05, -2.85, -2.65, -2.45, -2.25, -2.05, -1.85, -1.65,
        -1.45, -1.25, -1.05, -0.85, -0.65, -0.45, -0.25],
       [ 0.  ,  0.2 ,  0.4 ,  0.6 ,  0.8 ,  1.  ,  1.2 ,  1.4 ,  1.6 ,
         1.8 ,  2.  ,  2.2 ,  2.4 ,  2.6 ,  2.8 ,  3.  ],
       [-1.  , -0.8 , -0.6 , -0.4 , -0.2 ,  0.  ,  0.2 ,  0.4 ,  0.6 ,
         0.8 ,  1.  ,  1.2 ,  1.4 ,  1.6 ,  1.8 ,  2.  ]])

In [19]:
np.array([nsr.bg_V.grid_pos[0, :, 0, 0],
          nsr.bg_V.grid_pos[1, 0, :, 0],
          nsr.bg_V.grid_pos[2, 0, 0, :]])[:, 0]

array([-9.25, -6.  , -7.  ])

In [20]:
v000 = np.abs(rfst[:, :, np.newaxis] - np.array([
    nsr.fg_V.grid_pos[0, :, 0, 0], nsr.fg_V.grid_pos[1, 0, :, 0], nsr.fg_V.grid_pos[2, 0, 0, :]
])).argmin(axis=2)
v000.tolist()

[[15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],
 [15, 0, 6],

In [54]:
v001 = np.clip(v000-[1, 0, 0], a_min=None, a_max=15)
v010 = np.clip(v000-[0, 1, 0], a_min=None, a_max=15)
v011 = np.clip(v000-[0, 1, 1], a_min=None, a_max=15)
v100 = np.clip(v000-[1, 0, 0], a_min=None, a_max=15)
v101 = np.clip(v000-[1, 0, 1], a_min=None, a_max=15)
v110 = np.clip(v000-[1, 1, 0], a_min=None, a_max=15)
v111 = np.clip(v000-[1, 1, 1], a_min=None, a_max=15)

In [55]:
# np.clip(, a_min=None, a_max=15)
# ((fst-FG_ROUNDING_OFS)/abs(FG_STEP_SIZE)).tolist()
vXXX = np.clip(((fst-FG_ROUNDING_OFS)/abs(FG_STEP_SIZE)), a_min=None, a_max=15).tolist()

In [58]:
print(FG_STEP_SIZE)
for i in range(len(v000)):
    print(v000[i], v111[i], vXXX[i])

-0.20000000000000018
[0 6 9] [0.5218887134146617, 6.864050790012916, 9.645828236179463]


In [35]:
(fst-FG_ROUNDING_OFS)/abs(FG_STEP_SIZE)

array([[16.25, -0.  ,  5.  ],
       [16.25, -0.  ,  5.  ],
       [16.25, -0.  ,  5.  ],
       ...,
       [16.25,  0.  ,  5.  ],
       [16.25,  0.  ,  5.  ],
       [16.25,  0.  ,  5.  ]])

In [115]:
FG_STEP_SIZE

-0.20000000000000018

In [39]:
((fst+FG_ROUNDING_OFS)/FG_STEP_SIZE).tolist()

[[16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.999999999999996],
 [16.249999999999986, -0.0, 4.9999999999

In [102]:
np.array([
    nsr.fg_V.grid_pos[0, :, 0, 0], nsr.fg_V.grid_pos[1, 0, :, 0], nsr.fg_V.grid_pos[2, 0, 0, :]
])

array([[-3.25, -3.05, -2.85, -2.65, -2.45, -2.25, -2.05, -1.85, -1.65,
        -1.45, -1.25, -1.05, -0.85, -0.65, -0.45, -0.25],
       [ 0.  ,  0.2 ,  0.4 ,  0.6 ,  0.8 ,  1.  ,  1.2 ,  1.4 ,  1.6 ,
         1.8 ,  2.  ,  2.2 ,  2.4 ,  2.6 ,  2.8 ,  3.  ],
       [-1.  , -0.8 , -0.6 , -0.4 , -0.2 ,  0.  ,  0.2 ,  0.4 ,  0.6 ,
         0.8 ,  1.  ,  1.2 ,  1.4 ,  1.6 ,  1.8 ,  2.  ]])

In [103]:
nsr.fg_V.grid_pos[0, :, 0, 0][0]

-3.25

# ==============

In [11]:
nsr.fg_V.min_x

-3.25

In [12]:
_, st = nsr.query_pixel_sample_points(0, N_query_points=80, t_size=0.12,
                                           _pixel_grid_width_step=100.0,
                                           _pixel_grid_height_step=100.0,
                                           _scale=1.0)

0 001.png


In [42]:
((nsr.fg_V.min_x < st[:, :, 0]) & (st[:, :, 0] < nsr.fg_V.max_x) &
 (nsr.fg_V.min_y < st[:, :, 1]) & (st[:, :, 1] < nsr.fg_V.max_y) &
 (nsr.fg_V.min_z < st[:, :, 2]) & (st[:, :, 2] < nsr.fg_V.max_z)).astype(int)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
(nsr.fg_V.min_y < st[:, :, 1]) & (st[:, :, 1] < nsr.fg_V.max_y)

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])

In [40]:
((nsr.fg_V.min_z < st[:, :, 2]) & (st[:, :, 2] < nsr.fg_V.max_z)).astype(int)

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]])

In [31]:
st[:, :, 0]

array([[-2.79385646, -2.8108563 , -2.82785614, ..., -4.10284398,
        -4.11984382, -4.13684366],
       [-2.79289379, -2.80979049, -2.82668718, ..., -4.09393929,
        -4.11083598, -4.12773268],
       [-2.79197812, -2.80877671, -2.82557529, ..., -4.0854693 ,
        -4.10226789, -4.11906648],
       ...,
       [-2.45590444, -2.43669513, -2.41748582, ..., -0.97678776,
        -0.95757845, -0.93836914],
       [-2.45505029, -2.43574947, -2.41644865, ..., -0.96888691,
        -0.94958609, -0.93028526],
       [-2.45415167, -2.43475457, -2.41535746, ..., -0.96057467,
        -0.94117756, -0.92178046]])

In [32]:
nsr.fg_V.min_x, nsr.fg_V.max_x

(-3.25, -0.25)